name: cache-dependency-paths
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.10'
           cache: pip
           cache-dependency-path: ${{ github.action_path }}/requirements.txt
      - uses: PeterJCLaw/srcomp-validate-action@v0.2
